import "./globals.css";
import type { Metadata } from "next";
import Header from "./ui/header";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja" suppressHydrationWarning>
      {/* dark:bg-black dark:text-white */}
      <body className="min-h-screen">
        <Providers>
          <Header></Header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
